// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package ottercontrol

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type PlacementPolicy int64

const (
	PlacementPolicy_KEY_HASH PlacementPolicy = 0
	PlacementPolicy_ORDINAL_ROUND_ROBIN PlacementPolicy = 1
)

var knownPlacementPolicyValues = []PlacementPolicy{
	PlacementPolicy_KEY_HASH,
	PlacementPolicy_ORDINAL_ROUND_ROBIN,
}

func PlacementPolicyValues() iter.Seq[PlacementPolicy] {
	return func(yield func(PlacementPolicy) bool) {
		for _, v := range knownPlacementPolicyValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p PlacementPolicy) String() string {
	switch p {
	case PlacementPolicy_KEY_HASH: return "KEY_HASH"
	case PlacementPolicy_ORDINAL_ROUND_ROBIN: return "ORDINAL_ROUND_ROBIN"
	}
	return "<UNSET>"
}

func PlacementPolicyFromString(s string) (PlacementPolicy, error) {
	switch s {
	case "KEY_HASH": return PlacementPolicy_KEY_HASH, nil
	case "ORDINAL_ROUND_ROBIN": return PlacementPolicy_ORDINAL_ROUND_ROBIN, nil
	}
	return PlacementPolicy(0), fmt.Errorf("not a valid PlacementPolicy string")
}


func PlacementPolicyPtr(v PlacementPolicy) *PlacementPolicy { return &v }

func (p PlacementPolicy) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *PlacementPolicy) UnmarshalText(text []byte) error {
	q, err := PlacementPolicyFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *PlacementPolicy) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = PlacementPolicy(v)
	return nil
}

func (p *PlacementPolicy) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//  - Message
//  - ServerUnixMs
// 
type PingResponse struct {
	Message string `thrift:"message,1" db:"message" json:"message"`
	ServerUnixMs int64 `thrift:"server_unix_ms,2" db:"server_unix_ms" json:"server_unix_ms"`
}

func NewPingResponse() *PingResponse {
	return &PingResponse{}
}



func (p *PingResponse) GetMessage() string {
	return p.Message
}



func (p *PingResponse) GetServerUnixMs() int64 {
	return p.ServerUnixMs
}

func (p *PingResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *PingResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Message = v
	}
	return nil
}

func (p *PingResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.ServerUnixMs = v
	}
	return nil
}

func (p *PingResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "PingResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *PingResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "message", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:message: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Message)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.message (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:message: ", p), err)
	}
	return err
}

func (p *PingResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "server_unix_ms", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:server_unix_ms: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ServerUnixMs)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.server_unix_ms (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:server_unix_ms: ", p), err)
	}
	return err
}

func (p *PingResponse) Equals(other *PingResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Message != other.Message { return false }
	if p.ServerUnixMs != other.ServerUnixMs { return false }
	return true
}

func (p *PingResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingResponse(%+v)", *p)
}

func (p *PingResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.PingResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*PingResponse)(nil)

func (p *PingResponse) Validate() error {
	return nil
}

// Attributes:
//  - Slot
//  - NodeID
//  - Endpoint
//  - ChannelPath
// 
type ChannelSlot struct {
	Slot int32 `thrift:"slot,1" db:"slot" json:"slot"`
	NodeID string `thrift:"node_id,2" db:"node_id" json:"node_id"`
	Endpoint string `thrift:"endpoint,3" db:"endpoint" json:"endpoint"`
	ChannelPath string `thrift:"channel_path,4" db:"channel_path" json:"channel_path"`
}

func NewChannelSlot() *ChannelSlot {
	return &ChannelSlot{}
}



func (p *ChannelSlot) GetSlot() int32 {
	return p.Slot
}



func (p *ChannelSlot) GetNodeID() string {
	return p.NodeID
}



func (p *ChannelSlot) GetEndpoint() string {
	return p.Endpoint
}



func (p *ChannelSlot) GetChannelPath() string {
	return p.ChannelPath
}

func (p *ChannelSlot) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ChannelSlot) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Slot = v
	}
	return nil
}

func (p *ChannelSlot) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.NodeID = v
	}
	return nil
}

func (p *ChannelSlot) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Endpoint = v
	}
	return nil
}

func (p *ChannelSlot) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.ChannelPath = v
	}
	return nil
}

func (p *ChannelSlot) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ChannelSlot"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ChannelSlot) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "slot", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:slot: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Slot)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.slot (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:slot: ", p), err)
	}
	return err
}

func (p *ChannelSlot) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "node_id", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:node_id: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.NodeID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.node_id (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:node_id: ", p), err)
	}
	return err
}

func (p *ChannelSlot) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "endpoint", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:endpoint: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Endpoint)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.endpoint (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:endpoint: ", p), err)
	}
	return err
}

func (p *ChannelSlot) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "channel_path", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:channel_path: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.ChannelPath)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.channel_path (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:channel_path: ", p), err)
	}
	return err
}

func (p *ChannelSlot) Equals(other *ChannelSlot) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Slot != other.Slot { return false }
	if p.NodeID != other.NodeID { return false }
	if p.Endpoint != other.Endpoint { return false }
	if p.ChannelPath != other.ChannelPath { return false }
	return true
}

func (p *ChannelSlot) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChannelSlot(%+v)", *p)
}

func (p *ChannelSlot) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.ChannelSlot",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ChannelSlot)(nil)

func (p *ChannelSlot) Validate() error {
	return nil
}

// Attributes:
//  - ClientID
//  - AccessKeyID
//  - Bucket
//  - Epoch
//  - N
//  - Slots
//  - Policy
//  - LeaseExpiryUnixS
//  - Active
// 
type OtterChannelGrant struct {
	ClientID string `thrift:"client_id,1" db:"client_id" json:"client_id"`
	AccessKeyID string `thrift:"access_key_id,2" db:"access_key_id" json:"access_key_id"`
	Bucket string `thrift:"bucket,3" db:"bucket" json:"bucket"`
	Epoch int64 `thrift:"epoch,4" db:"epoch" json:"epoch"`
	N int32 `thrift:"n,5" db:"n" json:"n"`
	Slots []*ChannelSlot `thrift:"slots,6" db:"slots" json:"slots"`
	Policy PlacementPolicy `thrift:"policy,7" db:"policy" json:"policy"`
	LeaseExpiryUnixS int64 `thrift:"lease_expiry_unix_s,8" db:"lease_expiry_unix_s" json:"lease_expiry_unix_s"`
	Active bool `thrift:"active,9" db:"active" json:"active"`
}

func NewOtterChannelGrant() *OtterChannelGrant {
	return &OtterChannelGrant{}
}



func (p *OtterChannelGrant) GetClientID() string {
	return p.ClientID
}



func (p *OtterChannelGrant) GetAccessKeyID() string {
	return p.AccessKeyID
}



func (p *OtterChannelGrant) GetBucket() string {
	return p.Bucket
}



func (p *OtterChannelGrant) GetEpoch() int64 {
	return p.Epoch
}



func (p *OtterChannelGrant) GetN() int32 {
	return p.N
}



func (p *OtterChannelGrant) GetSlots() []*ChannelSlot {
	return p.Slots
}



func (p *OtterChannelGrant) GetPolicy() PlacementPolicy {
	return p.Policy
}



func (p *OtterChannelGrant) GetLeaseExpiryUnixS() int64 {
	return p.LeaseExpiryUnixS
}



func (p *OtterChannelGrant) GetActive() bool {
	return p.Active
}

func (p *OtterChannelGrant) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField9(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterChannelGrant) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ClientID = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.AccessKeyID = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Bucket = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Epoch = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.N = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*ChannelSlot, 0, size)
	p.Slots = tSlice
	for i := 0; i < size; i++ {
		_elem0 := &ChannelSlot{}
		if err := _elem0.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.Slots = append(p.Slots, _elem0)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *OtterChannelGrant) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		temp := PlacementPolicy(v)
		p.Policy = temp
	}
	return nil
}

func (p *OtterChannelGrant) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		p.LeaseExpiryUnixS = v
	}
	return nil
}

func (p *OtterChannelGrant) ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 9: ", err)
	} else {
		p.Active = v
	}
	return nil
}

func (p *OtterChannelGrant) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "OtterChannelGrant"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
		if err := p.writeField5(ctx, oprot); err != nil { return err }
		if err := p.writeField6(ctx, oprot); err != nil { return err }
		if err := p.writeField7(ctx, oprot); err != nil { return err }
		if err := p.writeField8(ctx, oprot); err != nil { return err }
		if err := p.writeField9(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterChannelGrant) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "client_id", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:client_id: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.ClientID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.client_id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:client_id: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "access_key_id", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:access_key_id: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.AccessKeyID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.access_key_id (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:access_key_id: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bucket", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:bucket: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Bucket)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bucket (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:bucket: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "epoch", thrift.I64, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:epoch: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.Epoch)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.epoch (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:epoch: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "n", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:n: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.N)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.n (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:n: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "slots", thrift.LIST, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:slots: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Slots)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Slots {
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:slots: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "policy", thrift.I32, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:policy: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Policy)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.policy (7) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:policy: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "lease_expiry_unix_s", thrift.I64, 8); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:lease_expiry_unix_s: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.LeaseExpiryUnixS)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.lease_expiry_unix_s (8) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 8:lease_expiry_unix_s: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "active", thrift.BOOL, 9); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:active: ", p), err)
	}
	if err := oprot.WriteBool(ctx, bool(p.Active)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.active (9) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 9:active: ", p), err)
	}
	return err
}

func (p *OtterChannelGrant) Equals(other *OtterChannelGrant) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.ClientID != other.ClientID { return false }
	if p.AccessKeyID != other.AccessKeyID { return false }
	if p.Bucket != other.Bucket { return false }
	if p.Epoch != other.Epoch { return false }
	if p.N != other.N { return false }
	if len(p.Slots) != len(other.Slots) { return false }
	for i, _tgt := range p.Slots {
		_src1 := other.Slots[i]
		if !_tgt.Equals(_src1) { return false }
	}
	if p.Policy != other.Policy { return false }
	if p.LeaseExpiryUnixS != other.LeaseExpiryUnixS { return false }
	if p.Active != other.Active { return false }
	return true
}

func (p *OtterChannelGrant) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterChannelGrant(%+v)", *p)
}

func (p *OtterChannelGrant) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterChannelGrant",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterChannelGrant)(nil)

func (p *OtterChannelGrant) Validate() error {
	return nil
}

// Attributes:
//  - Accepted
//  - CurrentEpoch
//  - Detail
// 
type UpsertGrantResponse struct {
	Accepted bool `thrift:"accepted,1" db:"accepted" json:"accepted"`
	CurrentEpoch int64 `thrift:"current_epoch,2" db:"current_epoch" json:"current_epoch"`
	Detail string `thrift:"detail,3" db:"detail" json:"detail"`
}

func NewUpsertGrantResponse() *UpsertGrantResponse {
	return &UpsertGrantResponse{}
}



func (p *UpsertGrantResponse) GetAccepted() bool {
	return p.Accepted
}



func (p *UpsertGrantResponse) GetCurrentEpoch() int64 {
	return p.CurrentEpoch
}



func (p *UpsertGrantResponse) GetDetail() string {
	return p.Detail
}

func (p *UpsertGrantResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpsertGrantResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Accepted = v
	}
	return nil
}

func (p *UpsertGrantResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.CurrentEpoch = v
	}
	return nil
}

func (p *UpsertGrantResponse) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Detail = v
	}
	return nil
}

func (p *UpsertGrantResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "UpsertGrantResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpsertGrantResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "accepted", thrift.BOOL, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:accepted: ", p), err)
	}
	if err := oprot.WriteBool(ctx, bool(p.Accepted)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.accepted (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:accepted: ", p), err)
	}
	return err
}

func (p *UpsertGrantResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "current_epoch", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:current_epoch: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.CurrentEpoch)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.current_epoch (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:current_epoch: ", p), err)
	}
	return err
}

func (p *UpsertGrantResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "detail", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:detail: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Detail)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.detail (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:detail: ", p), err)
	}
	return err
}

func (p *UpsertGrantResponse) Equals(other *UpsertGrantResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Accepted != other.Accepted { return false }
	if p.CurrentEpoch != other.CurrentEpoch { return false }
	if p.Detail != other.Detail { return false }
	return true
}

func (p *UpsertGrantResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertGrantResponse(%+v)", *p)
}

func (p *UpsertGrantResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.UpsertGrantResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UpsertGrantResponse)(nil)

func (p *UpsertGrantResponse) Validate() error {
	return nil
}

// Attributes:
//  - AccessKeyID
//  - Bucket
//  - Epoch
//  - ClientID
// 
type RevokeRequest struct {
	AccessKeyID string `thrift:"access_key_id,1" db:"access_key_id" json:"access_key_id"`
	Bucket string `thrift:"bucket,2" db:"bucket" json:"bucket"`
	Epoch int64 `thrift:"epoch,3" db:"epoch" json:"epoch"`
	ClientID string `thrift:"client_id,4" db:"client_id" json:"client_id"`
}

func NewRevokeRequest() *RevokeRequest {
	return &RevokeRequest{}
}



func (p *RevokeRequest) GetAccessKeyID() string {
	return p.AccessKeyID
}



func (p *RevokeRequest) GetBucket() string {
	return p.Bucket
}



func (p *RevokeRequest) GetEpoch() int64 {
	return p.Epoch
}



func (p *RevokeRequest) GetClientID() string {
	return p.ClientID
}

func (p *RevokeRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *RevokeRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.AccessKeyID = v
	}
	return nil
}

func (p *RevokeRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Bucket = v
	}
	return nil
}

func (p *RevokeRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Epoch = v
	}
	return nil
}

func (p *RevokeRequest) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.ClientID = v
	}
	return nil
}

func (p *RevokeRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "RevokeRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *RevokeRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "access_key_id", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:access_key_id: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.AccessKeyID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.access_key_id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:access_key_id: ", p), err)
	}
	return err
}

func (p *RevokeRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bucket", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:bucket: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Bucket)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bucket (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:bucket: ", p), err)
	}
	return err
}

func (p *RevokeRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "epoch", thrift.I64, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:epoch: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.Epoch)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.epoch (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:epoch: ", p), err)
	}
	return err
}

func (p *RevokeRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "client_id", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:client_id: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.ClientID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.client_id (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:client_id: ", p), err)
	}
	return err
}

func (p *RevokeRequest) Equals(other *RevokeRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.AccessKeyID != other.AccessKeyID { return false }
	if p.Bucket != other.Bucket { return false }
	if p.Epoch != other.Epoch { return false }
	if p.ClientID != other.ClientID { return false }
	return true
}

func (p *RevokeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RevokeRequest(%+v)", *p)
}

func (p *RevokeRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.RevokeRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*RevokeRequest)(nil)

func (p *RevokeRequest) Validate() error {
	return nil
}

// Attributes:
//  - Revoked
//  - Detail
// 
type RevokeGrantResponse struct {
	Revoked bool `thrift:"revoked,1" db:"revoked" json:"revoked"`
	Detail string `thrift:"detail,2" db:"detail" json:"detail"`
}

func NewRevokeGrantResponse() *RevokeGrantResponse {
	return &RevokeGrantResponse{}
}



func (p *RevokeGrantResponse) GetRevoked() bool {
	return p.Revoked
}



func (p *RevokeGrantResponse) GetDetail() string {
	return p.Detail
}

func (p *RevokeGrantResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *RevokeGrantResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Revoked = v
	}
	return nil
}

func (p *RevokeGrantResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Detail = v
	}
	return nil
}

func (p *RevokeGrantResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "RevokeGrantResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *RevokeGrantResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "revoked", thrift.BOOL, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:revoked: ", p), err)
	}
	if err := oprot.WriteBool(ctx, bool(p.Revoked)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.revoked (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:revoked: ", p), err)
	}
	return err
}

func (p *RevokeGrantResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "detail", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:detail: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Detail)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.detail (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:detail: ", p), err)
	}
	return err
}

func (p *RevokeGrantResponse) Equals(other *RevokeGrantResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Revoked != other.Revoked { return false }
	if p.Detail != other.Detail { return false }
	return true
}

func (p *RevokeGrantResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RevokeGrantResponse(%+v)", *p)
}

func (p *RevokeGrantResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.RevokeGrantResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*RevokeGrantResponse)(nil)

func (p *RevokeGrantResponse) Validate() error {
	return nil
}

type OtterControl interface {
	// Parameters:
	//  - Caller
	// 
	Ping(ctx context.Context, caller string) (_r *PingResponse, _err error)
	// Parameters:
	//  - Grant
	// 
	UpsertChannelGrant(ctx context.Context, grant *OtterChannelGrant) (_r *UpsertGrantResponse, _err error)
	// Parameters:
	//  - Req
	// 
	RevokeChannelGrant(ctx context.Context, req *RevokeRequest) (_r *RevokeGrantResponse, _err error)
}

type OtterControlClient struct {
	c thrift.TClient
	meta thrift.ResponseMeta
}

func NewOtterControlClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *OtterControlClient {
	return &OtterControlClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewOtterControlClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *OtterControlClient {
	return &OtterControlClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewOtterControlClient(c thrift.TClient) *OtterControlClient {
	return &OtterControlClient{
		c: c,
	}
}

func (p *OtterControlClient) Client_() thrift.TClient {
	return p.c
}

func (p *OtterControlClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *OtterControlClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//  - Caller
// 
func (p *OtterControlClient) Ping(ctx context.Context, caller string) (_r *PingResponse, _err error) {
	var _args2 OtterControlPingArgs
	_args2.Caller = caller
	var _result4 OtterControlPingResult
	var _meta3 thrift.ResponseMeta
	_meta3, _err = p.Client_().Call(ctx, "ping", &_args2, &_result4)
	p.SetLastResponseMeta_(_meta3)
	if _err != nil {
		return
	}
	if _ret5 := _result4.GetSuccess(); _ret5 != nil {
		return _ret5, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "ping failed: unknown result")
}

// Parameters:
//  - Grant
// 
func (p *OtterControlClient) UpsertChannelGrant(ctx context.Context, grant *OtterChannelGrant) (_r *UpsertGrantResponse, _err error) {
	var _args6 OtterControlUpsertChannelGrantArgs
	_args6.Grant = grant
	var _result8 OtterControlUpsertChannelGrantResult
	var _meta7 thrift.ResponseMeta
	_meta7, _err = p.Client_().Call(ctx, "upsertChannelGrant", &_args6, &_result8)
	p.SetLastResponseMeta_(_meta7)
	if _err != nil {
		return
	}
	if _ret9 := _result8.GetSuccess(); _ret9 != nil {
		return _ret9, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "upsertChannelGrant failed: unknown result")
}

// Parameters:
//  - Req
// 
func (p *OtterControlClient) RevokeChannelGrant(ctx context.Context, req *RevokeRequest) (_r *RevokeGrantResponse, _err error) {
	var _args10 OtterControlRevokeChannelGrantArgs
	_args10.Req = req
	var _result12 OtterControlRevokeChannelGrantResult
	var _meta11 thrift.ResponseMeta
	_meta11, _err = p.Client_().Call(ctx, "revokeChannelGrant", &_args10, &_result12)
	p.SetLastResponseMeta_(_meta11)
	if _err != nil {
		return
	}
	if _ret13 := _result12.GetSuccess(); _ret13 != nil {
		return _ret13, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "revokeChannelGrant failed: unknown result")
}

type OtterControlProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler OtterControl
}

func (p *OtterControlProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *OtterControlProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *OtterControlProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewOtterControlProcessor(handler OtterControl) *OtterControlProcessor {

	self14 := &OtterControlProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
	self14.processorMap["ping"] = &otterControlProcessorPing{handler:handler}
	self14.processorMap["upsertChannelGrant"] = &otterControlProcessorUpsertChannelGrant{handler:handler}
	self14.processorMap["revokeChannelGrant"] = &otterControlProcessorRevokeChannelGrant{handler:handler}
	return self14
}

func (p *OtterControlProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil { return false, thrift.WrapTException(err2) }
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x15 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x15.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x15
}

type otterControlProcessorPing struct {
	handler OtterControl
}

func (p *otterControlProcessorPing) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err16 thrift.TException
	args := OtterControlPingArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "ping", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := OtterControlPingResult{}
	if retval, err2 := p.handler.Ping(ctx, args.Caller); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc17 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ping: " + err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "ping", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err16 = thrift.WrapTException(err2)
		}
		if err2 := _exc17.Write(ctx, oprot); _write_err16 == nil && err2 != nil {
			_write_err16 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err16 == nil && err2 != nil {
			_write_err16 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err16 == nil && err2 != nil {
			_write_err16 = thrift.WrapTException(err2)
		}
		if _write_err16 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err16,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "ping", thrift.REPLY, seqId); err2 != nil {
		_write_err16 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err16 == nil && err2 != nil {
		_write_err16 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err16 == nil && err2 != nil {
		_write_err16 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err16 == nil && err2 != nil {
		_write_err16 = thrift.WrapTException(err2)
	}
	if _write_err16 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err16,
			EndpointError: err,
		}
	}
	return true, err
}

type otterControlProcessorUpsertChannelGrant struct {
	handler OtterControl
}

func (p *otterControlProcessorUpsertChannelGrant) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err18 thrift.TException
	args := OtterControlUpsertChannelGrantArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "upsertChannelGrant", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := OtterControlUpsertChannelGrantResult{}
	if retval, err2 := p.handler.UpsertChannelGrant(ctx, args.Grant); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc19 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing upsertChannelGrant: " + err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "upsertChannelGrant", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err18 = thrift.WrapTException(err2)
		}
		if err2 := _exc19.Write(ctx, oprot); _write_err18 == nil && err2 != nil {
			_write_err18 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err18 == nil && err2 != nil {
			_write_err18 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err18 == nil && err2 != nil {
			_write_err18 = thrift.WrapTException(err2)
		}
		if _write_err18 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err18,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "upsertChannelGrant", thrift.REPLY, seqId); err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if _write_err18 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err18,
			EndpointError: err,
		}
	}
	return true, err
}

type otterControlProcessorRevokeChannelGrant struct {
	handler OtterControl
}

func (p *otterControlProcessorRevokeChannelGrant) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err20 thrift.TException
	args := OtterControlRevokeChannelGrantArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "revokeChannelGrant", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := OtterControlRevokeChannelGrantResult{}
	if retval, err2 := p.handler.RevokeChannelGrant(ctx, args.Req); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc21 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing revokeChannelGrant: " + err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "revokeChannelGrant", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err20 = thrift.WrapTException(err2)
		}
		if err2 := _exc21.Write(ctx, oprot); _write_err20 == nil && err2 != nil {
			_write_err20 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err20 == nil && err2 != nil {
			_write_err20 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err20 == nil && err2 != nil {
			_write_err20 = thrift.WrapTException(err2)
		}
		if _write_err20 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err20,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "revokeChannelGrant", thrift.REPLY, seqId); err2 != nil {
		_write_err20 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err20 == nil && err2 != nil {
		_write_err20 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err20 == nil && err2 != nil {
		_write_err20 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err20 == nil && err2 != nil {
		_write_err20 = thrift.WrapTException(err2)
	}
	if _write_err20 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err20,
			EndpointError: err,
		}
	}
	return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Caller
// 
type OtterControlPingArgs struct {
	Caller string `thrift:"caller,1" db:"caller" json:"caller"`
}

func NewOtterControlPingArgs() *OtterControlPingArgs {
	return &OtterControlPingArgs{}
}



func (p *OtterControlPingArgs) GetCaller() string {
	return p.Caller
}

func (p *OtterControlPingArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlPingArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Caller = v
	}
	return nil
}

func (p *OtterControlPingArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ping_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlPingArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "caller", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:caller: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Caller)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.caller (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:caller: ", p), err)
	}
	return err
}

func (p *OtterControlPingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlPingArgs(%+v)", *p)
}

func (p *OtterControlPingArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlPingArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlPingArgs)(nil)

// Attributes:
//  - Success
// 
type OtterControlPingResult struct {
	Success *PingResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewOtterControlPingResult() *OtterControlPingResult {
	return &OtterControlPingResult{}
}

var OtterControlPingResult_Success_DEFAULT *PingResponse

func (p *OtterControlPingResult) GetSuccess() *PingResponse {
	if !p.IsSetSuccess() {
		return OtterControlPingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OtterControlPingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OtterControlPingResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlPingResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &PingResponse{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *OtterControlPingResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ping_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlPingResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *OtterControlPingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlPingResult(%+v)", *p)
}

func (p *OtterControlPingResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlPingResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlPingResult)(nil)

// Attributes:
//  - Grant
// 
type OtterControlUpsertChannelGrantArgs struct {
	Grant *OtterChannelGrant `thrift:"grant,1" db:"grant" json:"grant"`
}

func NewOtterControlUpsertChannelGrantArgs() *OtterControlUpsertChannelGrantArgs {
	return &OtterControlUpsertChannelGrantArgs{}
}

var OtterControlUpsertChannelGrantArgs_Grant_DEFAULT *OtterChannelGrant

func (p *OtterControlUpsertChannelGrantArgs) GetGrant() *OtterChannelGrant {
	if !p.IsSetGrant() {
		return OtterControlUpsertChannelGrantArgs_Grant_DEFAULT
	}
	return p.Grant
}

func (p *OtterControlUpsertChannelGrantArgs) IsSetGrant() bool {
	return p.Grant != nil
}

func (p *OtterControlUpsertChannelGrantArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Grant = &OtterChannelGrant{}
	if err := p.Grant.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Grant), err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "upsertChannelGrant_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "grant", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:grant: ", p), err)
	}
	if err := p.Grant.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Grant), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:grant: ", p), err)
	}
	return err
}

func (p *OtterControlUpsertChannelGrantArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlUpsertChannelGrantArgs(%+v)", *p)
}

func (p *OtterControlUpsertChannelGrantArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlUpsertChannelGrantArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlUpsertChannelGrantArgs)(nil)

// Attributes:
//  - Success
// 
type OtterControlUpsertChannelGrantResult struct {
	Success *UpsertGrantResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewOtterControlUpsertChannelGrantResult() *OtterControlUpsertChannelGrantResult {
	return &OtterControlUpsertChannelGrantResult{}
}

var OtterControlUpsertChannelGrantResult_Success_DEFAULT *UpsertGrantResponse

func (p *OtterControlUpsertChannelGrantResult) GetSuccess() *UpsertGrantResponse {
	if !p.IsSetSuccess() {
		return OtterControlUpsertChannelGrantResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OtterControlUpsertChannelGrantResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OtterControlUpsertChannelGrantResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &UpsertGrantResponse{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "upsertChannelGrant_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlUpsertChannelGrantResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *OtterControlUpsertChannelGrantResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlUpsertChannelGrantResult(%+v)", *p)
}

func (p *OtterControlUpsertChannelGrantResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlUpsertChannelGrantResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlUpsertChannelGrantResult)(nil)

// Attributes:
//  - Req
// 
type OtterControlRevokeChannelGrantArgs struct {
	Req *RevokeRequest `thrift:"req,1" db:"req" json:"req"`
}

func NewOtterControlRevokeChannelGrantArgs() *OtterControlRevokeChannelGrantArgs {
	return &OtterControlRevokeChannelGrantArgs{}
}

var OtterControlRevokeChannelGrantArgs_Req_DEFAULT *RevokeRequest

func (p *OtterControlRevokeChannelGrantArgs) GetReq() *RevokeRequest {
	if !p.IsSetReq() {
		return OtterControlRevokeChannelGrantArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OtterControlRevokeChannelGrantArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OtterControlRevokeChannelGrantArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Req = &RevokeRequest{}
	if err := p.Req.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "revokeChannelGrant_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err)
	}
	if err := p.Req.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err)
	}
	return err
}

func (p *OtterControlRevokeChannelGrantArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlRevokeChannelGrantArgs(%+v)", *p)
}

func (p *OtterControlRevokeChannelGrantArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlRevokeChannelGrantArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlRevokeChannelGrantArgs)(nil)

// Attributes:
//  - Success
// 
type OtterControlRevokeChannelGrantResult struct {
	Success *RevokeGrantResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewOtterControlRevokeChannelGrantResult() *OtterControlRevokeChannelGrantResult {
	return &OtterControlRevokeChannelGrantResult{}
}

var OtterControlRevokeChannelGrantResult_Success_DEFAULT *RevokeGrantResponse

func (p *OtterControlRevokeChannelGrantResult) GetSuccess() *RevokeGrantResponse {
	if !p.IsSetSuccess() {
		return OtterControlRevokeChannelGrantResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OtterControlRevokeChannelGrantResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OtterControlRevokeChannelGrantResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &RevokeGrantResponse{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "revokeChannelGrant_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OtterControlRevokeChannelGrantResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *OtterControlRevokeChannelGrantResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtterControlRevokeChannelGrantResult(%+v)", *p)
}

func (p *OtterControlRevokeChannelGrantResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*ottercontrol.OtterControlRevokeChannelGrantResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OtterControlRevokeChannelGrantResult)(nil)


