// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.6
// source: otter_control.proto

// OtterControlService — the JFL -> Otter gateway control-plane RPC, over gRPC.
//
// This is the standalone (laptop-buildable) contract for the receiver loopback test.
// It mirrors the proven Thrift OtterControl wire (poc0-jfl-thrift) so the grant
// subsystem (otter/grant) is exercised UNCHANGED under a gRPC transport. The
// production shape under src/grpc/core/otter adds core.common.RequestContext on
// requests and core.common.ErrorMessageInfo on responses (CDM convention) — omitted
// here exactly as the Thrift PoC omitted RequestContext.

package ottercontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	OtterControlService_Ping_FullMethodName               = "/otter.control.v1.OtterControlService/Ping"
	OtterControlService_UpsertChannelGrant_FullMethodName = "/otter.control.v1.OtterControlService/UpsertChannelGrant"
	OtterControlService_RevokeChannelGrant_FullMethodName = "/otter.control.v1.OtterControlService/RevokeChannelGrant"
)

// OtterControlServiceClient is the client API for OtterControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtterControlServiceClient interface {
	// liveness / mTLS-handshake probe
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// JFL pushes a grant; idempotent by (access_key_id, bucket); epoch guards ordering
	UpsertChannelGrant(ctx context.Context, in *UpsertChannelGrantRequest, opts ...grpc.CallOption) (*UpsertChannelGrantResponse, error)
	// offboard / rotate / retire a grant from the hot cache
	RevokeChannelGrant(ctx context.Context, in *RevokeChannelGrantRequest, opts ...grpc.CallOption) (*RevokeChannelGrantResponse, error)
}

type otterControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOtterControlServiceClient(cc grpc.ClientConnInterface) OtterControlServiceClient {
	return &otterControlServiceClient{cc}
}

func (c *otterControlServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OtterControlService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otterControlServiceClient) UpsertChannelGrant(ctx context.Context, in *UpsertChannelGrantRequest, opts ...grpc.CallOption) (*UpsertChannelGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertChannelGrantResponse)
	err := c.cc.Invoke(ctx, OtterControlService_UpsertChannelGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otterControlServiceClient) RevokeChannelGrant(ctx context.Context, in *RevokeChannelGrantRequest, opts ...grpc.CallOption) (*RevokeChannelGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeChannelGrantResponse)
	err := c.cc.Invoke(ctx, OtterControlService_RevokeChannelGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtterControlServiceServer is the server API for OtterControlService service.
// All implementations must embed UnimplementedOtterControlServiceServer
// for forward compatibility
type OtterControlServiceServer interface {
	// liveness / mTLS-handshake probe
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// JFL pushes a grant; idempotent by (access_key_id, bucket); epoch guards ordering
	UpsertChannelGrant(context.Context, *UpsertChannelGrantRequest) (*UpsertChannelGrantResponse, error)
	// offboard / rotate / retire a grant from the hot cache
	RevokeChannelGrant(context.Context, *RevokeChannelGrantRequest) (*RevokeChannelGrantResponse, error)
	mustEmbedUnimplementedOtterControlServiceServer()
}

// UnimplementedOtterControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOtterControlServiceServer struct {
}

func (UnimplementedOtterControlServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOtterControlServiceServer) UpsertChannelGrant(context.Context, *UpsertChannelGrantRequest) (*UpsertChannelGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertChannelGrant not implemented")
}
func (UnimplementedOtterControlServiceServer) RevokeChannelGrant(context.Context, *RevokeChannelGrantRequest) (*RevokeChannelGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeChannelGrant not implemented")
}
func (UnimplementedOtterControlServiceServer) mustEmbedUnimplementedOtterControlServiceServer() {}

// UnsafeOtterControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtterControlServiceServer will
// result in compilation errors.
type UnsafeOtterControlServiceServer interface {
	mustEmbedUnimplementedOtterControlServiceServer()
}

func RegisterOtterControlServiceServer(s grpc.ServiceRegistrar, srv OtterControlServiceServer) {
	s.RegisterService(&OtterControlService_ServiceDesc, srv)
}

func _OtterControlService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtterControlServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtterControlService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtterControlServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtterControlService_UpsertChannelGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertChannelGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtterControlServiceServer).UpsertChannelGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtterControlService_UpsertChannelGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtterControlServiceServer).UpsertChannelGrant(ctx, req.(*UpsertChannelGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtterControlService_RevokeChannelGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeChannelGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtterControlServiceServer).RevokeChannelGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtterControlService_RevokeChannelGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtterControlServiceServer).RevokeChannelGrant(ctx, req.(*RevokeChannelGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OtterControlService_ServiceDesc is the grpc.ServiceDesc for OtterControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OtterControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otter.control.v1.OtterControlService",
	HandlerType: (*OtterControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OtterControlService_Ping_Handler,
		},
		{
			MethodName: "UpsertChannelGrant",
			Handler:    _OtterControlService_UpsertChannelGrant_Handler,
		},
		{
			MethodName: "RevokeChannelGrant",
			Handler:    _OtterControlService_RevokeChannelGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otter_control.proto",
}
