// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.6
// source: otter_control.proto

// OtterControlService — the JFL -> Otter gateway control-plane RPC, over gRPC.
//
// This is the standalone (laptop-buildable) contract for the receiver loopback test.
// It mirrors the proven Thrift OtterControl wire (poc0-jfl-thrift) so the grant
// subsystem (otter/grant) is exercised UNCHANGED under a gRPC transport. The
// production shape under src/grpc/core/otter adds core.common.RequestContext on
// requests and core.common.ErrorMessageInfo on responses (CDM convention) — omitted
// here exactly as the Thrift PoC omitted RequestContext.

package ottercontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlacementPolicy int32

const (
	PlacementPolicy_KEY_HASH            PlacementPolicy = 0
	PlacementPolicy_ORDINAL_ROUND_ROBIN PlacementPolicy = 1
)

// Enum value maps for PlacementPolicy.
var (
	PlacementPolicy_name = map[int32]string{
		0: "KEY_HASH",
		1: "ORDINAL_ROUND_ROBIN",
	}
	PlacementPolicy_value = map[string]int32{
		"KEY_HASH":            0,
		"ORDINAL_ROUND_ROBIN": 1,
	}
)

func (x PlacementPolicy) Enum() *PlacementPolicy {
	p := new(PlacementPolicy)
	*p = x
	return p
}

func (x PlacementPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_otter_control_proto_enumTypes[0].Descriptor()
}

func (PlacementPolicy) Type() protoreflect.EnumType {
	return &file_otter_control_proto_enumTypes[0]
}

func (x PlacementPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementPolicy.Descriptor instead.
func (PlacementPolicy) EnumDescriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{0}
}

type ChannelSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot        int32  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	NodeId      string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint    string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ChannelPath string `protobuf:"bytes,4,opt,name=channel_path,json=channelPath,proto3" json:"channel_path,omitempty"`
}

func (x *ChannelSlot) Reset() {
	*x = ChannelSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSlot) ProtoMessage() {}

func (x *ChannelSlot) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSlot.ProtoReflect.Descriptor instead.
func (*ChannelSlot) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelSlot) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ChannelSlot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChannelSlot) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ChannelSlot) GetChannelPath() string {
	if x != nil {
		return x.ChannelPath
	}
	return ""
}

// The grant: "which client (by access key), which bucket, which channels."
type OtterChannelGrant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId         string          `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                              // logical client (IAM principal) — provenance only
	AccessKeyId      string          `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`                   // SigV4 key the client signs with -> the join key
	Bucket           string          `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`                                                  // the bucket this grant authorizes
	Epoch            int64           `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`                                                   // monotonic version, frozen per (access_key_id,bucket); higher wins
	N                int32           `protobuf:"varint,5,opt,name=n,proto3" json:"n,omitempty"`                                                           // channel count (== slots.size; validated on receipt)
	Slots            []*ChannelSlot  `protobuf:"bytes,6,rep,name=slots,proto3" json:"slots,omitempty"`                                                    // ordered slot -> owner: the channel-set
	Policy           PlacementPolicy `protobuf:"varint,7,opt,name=policy,proto3,enum=otter.control.v1.PlacementPolicy" json:"policy,omitempty"`           // KEY_HASH | ORDINAL_ROUND_ROBIN
	LeaseExpiryUnixS int64           `protobuf:"varint,8,opt,name=lease_expiry_unix_s,json=leaseExpiryUnixS,proto3" json:"lease_expiry_unix_s,omitempty"` // optional TTL (revoke-by-expiry); 0 = none
	Active           bool            `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`                                                 // false = soft-disable
}

func (x *OtterChannelGrant) Reset() {
	*x = OtterChannelGrant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtterChannelGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtterChannelGrant) ProtoMessage() {}

func (x *OtterChannelGrant) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtterChannelGrant.ProtoReflect.Descriptor instead.
func (*OtterChannelGrant) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{1}
}

func (x *OtterChannelGrant) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OtterChannelGrant) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *OtterChannelGrant) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *OtterChannelGrant) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *OtterChannelGrant) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *OtterChannelGrant) GetSlots() []*ChannelSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *OtterChannelGrant) GetPolicy() PlacementPolicy {
	if x != nil {
		return x.Policy
	}
	return PlacementPolicy_KEY_HASH
}

func (x *OtterChannelGrant) GetLeaseExpiryUnixS() int64 {
	if x != nil {
		return x.LeaseExpiryUnixS
	}
	return 0
}

func (x *OtterChannelGrant) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServerUnixMs int64  `protobuf:"varint,2,opt,name=server_unix_ms,json=serverUnixMs,proto3" json:"server_unix_ms,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetServerUnixMs() int64 {
	if x != nil {
		return x.ServerUnixMs
	}
	return 0
}

type UpsertChannelGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grant *OtterChannelGrant `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (x *UpsertChannelGrantRequest) Reset() {
	*x = UpsertChannelGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertChannelGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertChannelGrantRequest) ProtoMessage() {}

func (x *UpsertChannelGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertChannelGrantRequest.ProtoReflect.Descriptor instead.
func (*UpsertChannelGrantRequest) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertChannelGrantRequest) GetGrant() *OtterChannelGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type UpsertChannelGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted     bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                             // false if an equal-or-newer epoch already won
	CurrentEpoch int64  `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"` // the epoch now in effect (== grant.epoch on accept; the winner on reject)
	Detail       string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *UpsertChannelGrantResponse) Reset() {
	*x = UpsertChannelGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertChannelGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertChannelGrantResponse) ProtoMessage() {}

func (x *UpsertChannelGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertChannelGrantResponse.ProtoReflect.Descriptor instead.
func (*UpsertChannelGrantResponse) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertChannelGrantResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpsertChannelGrantResponse) GetCurrentEpoch() int64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *UpsertChannelGrantResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Revoke is keyed by the access_key_id (Otter's join key), not client_id.
type RevokeChannelGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKeyId string `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	Bucket      string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Epoch       int64  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`                      // guard: only revoke if >= the cached epoch
	ClientId    string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // provenance (optional)
}

func (x *RevokeChannelGrantRequest) Reset() {
	*x = RevokeChannelGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeChannelGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeChannelGrantRequest) ProtoMessage() {}

func (x *RevokeChannelGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeChannelGrantRequest.ProtoReflect.Descriptor instead.
func (*RevokeChannelGrantRequest) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeChannelGrantRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *RevokeChannelGrantRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RevokeChannelGrantRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RevokeChannelGrantRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RevokeChannelGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revoked bool   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Detail  string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *RevokeChannelGrantResponse) Reset() {
	*x = RevokeChannelGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otter_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeChannelGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeChannelGrantResponse) ProtoMessage() {}

func (x *RevokeChannelGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeChannelGrantResponse.ProtoReflect.Descriptor instead.
func (*RevokeChannelGrantResponse) Descriptor() ([]byte, []int) {
	return file_otter_control_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeChannelGrantResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeChannelGrantResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_otter_control_proto protoreflect.FileDescriptor

var file_otter_control_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x79, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x61,
	0x74, 0x68, 0x22, 0xc7, 0x02, 0x0a, 0x11, 0x4f, 0x74, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x6e, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x2d, 0x0a, 0x13, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x55,
	0x6e, 0x69, 0x78, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x25, 0x0a, 0x0b,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x78, 0x4d, 0x73, 0x22, 0x56, 0x0a, 0x19, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x39, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x74, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x75, 0x0a, 0x1a, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x8a, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x4e, 0x0a, 0x1a, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2a,
	0x38, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x0c, 0x0a, 0x08, 0x4b, 0x45, 0x59, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52, 0x44, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x52, 0x4f, 0x55, 0x4e,
	0x44, 0x5f, 0x52, 0x4f, 0x42, 0x49, 0x4e, 0x10, 0x01, 0x32, 0xbe, 0x02, 0x0a, 0x13, 0x4f, 0x74,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x45, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x2b,
	0x2e, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x12, 0x52, 0x65, 0x76,
	0x6f, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12,
	0x2b, 0x2e, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x67, 0x77, 0x2f, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x62, 0x3b, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_otter_control_proto_rawDescOnce sync.Once
	file_otter_control_proto_rawDescData = file_otter_control_proto_rawDesc
)

func file_otter_control_proto_rawDescGZIP() []byte {
	file_otter_control_proto_rawDescOnce.Do(func() {
		file_otter_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_otter_control_proto_rawDescData)
	})
	return file_otter_control_proto_rawDescData
}

var file_otter_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_otter_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_otter_control_proto_goTypes = []any{
	(PlacementPolicy)(0),               // 0: otter.control.v1.PlacementPolicy
	(*ChannelSlot)(nil),                // 1: otter.control.v1.ChannelSlot
	(*OtterChannelGrant)(nil),          // 2: otter.control.v1.OtterChannelGrant
	(*PingRequest)(nil),                // 3: otter.control.v1.PingRequest
	(*PingResponse)(nil),               // 4: otter.control.v1.PingResponse
	(*UpsertChannelGrantRequest)(nil),  // 5: otter.control.v1.UpsertChannelGrantRequest
	(*UpsertChannelGrantResponse)(nil), // 6: otter.control.v1.UpsertChannelGrantResponse
	(*RevokeChannelGrantRequest)(nil),  // 7: otter.control.v1.RevokeChannelGrantRequest
	(*RevokeChannelGrantResponse)(nil), // 8: otter.control.v1.RevokeChannelGrantResponse
}
var file_otter_control_proto_depIdxs = []int32{
	1, // 0: otter.control.v1.OtterChannelGrant.slots:type_name -> otter.control.v1.ChannelSlot
	0, // 1: otter.control.v1.OtterChannelGrant.policy:type_name -> otter.control.v1.PlacementPolicy
	2, // 2: otter.control.v1.UpsertChannelGrantRequest.grant:type_name -> otter.control.v1.OtterChannelGrant
	3, // 3: otter.control.v1.OtterControlService.Ping:input_type -> otter.control.v1.PingRequest
	5, // 4: otter.control.v1.OtterControlService.UpsertChannelGrant:input_type -> otter.control.v1.UpsertChannelGrantRequest
	7, // 5: otter.control.v1.OtterControlService.RevokeChannelGrant:input_type -> otter.control.v1.RevokeChannelGrantRequest
	4, // 6: otter.control.v1.OtterControlService.Ping:output_type -> otter.control.v1.PingResponse
	6, // 7: otter.control.v1.OtterControlService.UpsertChannelGrant:output_type -> otter.control.v1.UpsertChannelGrantResponse
	8, // 8: otter.control.v1.OtterControlService.RevokeChannelGrant:output_type -> otter.control.v1.RevokeChannelGrantResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_otter_control_proto_init() }
func file_otter_control_proto_init() {
	if File_otter_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_otter_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OtterChannelGrant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertChannelGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertChannelGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RevokeChannelGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otter_control_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RevokeChannelGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otter_control_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otter_control_proto_goTypes,
		DependencyIndexes: file_otter_control_proto_depIdxs,
		EnumInfos:         file_otter_control_proto_enumTypes,
		MessageInfos:      file_otter_control_proto_msgTypes,
	}.Build()
	File_otter_control_proto = out.File
	file_otter_control_proto_rawDesc = nil
	file_otter_control_proto_goTypes = nil
	file_otter_control_proto_depIdxs = nil
}
